name = "BernoulliMap"
uuid = "3703d90c-4a5c-4ebb-a2a0-1dfb5a33ab86"
authors = ["Milan <milankloewer@gmx.de> and contributors"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
